In [1]:
import numpy as np

# Define the L1-norm function |x|
def l1_norm(x):
    return np.abs(x)

# Define the subgradient of the L1-norm at a given point x
def subgradient_l1_norm(x):
    if x > 0:
        return 1.0
    elif x < 0:
        return -1.0
    else:
        # Return any value between -1 and 1 as a subgradient at x=0
        return np.random.uniform(-1, 1)




In [2]:
# Initialize the starting point for optimization
x = 2.0

# Set hyperparameters
learning_rate = 0.1
num_iterations = 10

# Perform gradient descent using surrogate gradients
for i in range(num_iterations):
    gradient = subgradient_l1_norm(x)
    x -= learning_rate * gradient
    print(f"Iteration {i+1}: x = {x}, L1-norm = {l1_norm(x)}")

print("Optimal x:", x)
print("L1-norm at optimal x:", l1_norm(x))

Iteration 1: x = 1.9, L1-norm = 1.9
Iteration 2: x = 1.7999999999999998, L1-norm = 1.7999999999999998
Iteration 3: x = 1.6999999999999997, L1-norm = 1.6999999999999997
Iteration 4: x = 1.5999999999999996, L1-norm = 1.5999999999999996
Iteration 5: x = 1.4999999999999996, L1-norm = 1.4999999999999996
Iteration 6: x = 1.3999999999999995, L1-norm = 1.3999999999999995
Iteration 7: x = 1.2999999999999994, L1-norm = 1.2999999999999994
Iteration 8: x = 1.1999999999999993, L1-norm = 1.1999999999999993
Iteration 9: x = 1.0999999999999992, L1-norm = 1.0999999999999992
Iteration 10: x = 0.9999999999999992, L1-norm = 0.9999999999999992
Optimal x: 0.9999999999999992
L1-norm at optimal x: 0.9999999999999992


In [5]:
import numpy as np
from scipy.linalg import expm

def create_matrix_with_determinant(d):
    # Create a random 3x3 matrix
    A = np.random.rand(3, 3)
    
    # Use the matrix exponential to ensure a positive determinant
    A = expm(A - A.T)
    
    # Scale the matrix to achieve the desired determinant
    determinant_A = np.linalg.det(A)
    scaling_factor = (d / determinant_A) ** (1/3)
    A = A * scaling_factor
    
    return A




In [6]:
# Specify the desired determinant
desired_determinant = 10.0

# Generate the 3x3 matrix with the desired determinant
resulting_matrix = create_matrix_with_determinant(desired_determinant)

print("Matrix with Determinant", desired_determinant)
print(resulting_matrix)
print("Determinant of the generated matrix:", np.linalg.det(resulting_matrix))

Matrix with Determinant 10.0
[[ 1.98824264 -0.34237828 -0.75581556]
 [ 0.58885918  1.96483011  0.65899646]
 [ 0.58457241 -0.81474449  1.90684434]]
Determinant of the generated matrix: 10.000000000000002
